// @generated
type DataStruct =
    <::icu::collator::provider::CollationMetadataV1Marker as ::icu_provider::DataMarker>::Yokeable;
pub fn lookup(locale: &icu_provider::DataLocale) -> Option<&'static DataStruct> {
    static KEYS: [&str; 117usize] = [
        "af",
        "am",
        "ar",
        "ar-u-co-compat",
        "as",
        "az",
        "be",
        "bg",
        "bn",
        "bn-u-co-trad",
        "bo",
        "br",
        "bs",
        "bs-Cyrl",
        "ceb",
        "chr",
        "cs",
        "cy",
        "da",
        "de-AT-u-co-phonebk",
        "de-u-co-phonebk",
        "dsb",
        "ee",
        "el",
        "en-US-posix",
        "eo",
        "es",
        "es-u-co-trad",
        "et",
        "fa",
        "fa-AF",
        "ff-Adlm",
        "fi",
        "fi-u-co-trad",
        "fil",
        "fo",
        "fr-CA",
        "fy",
        "gl",
        "gu",
        "ha",
        "haw",
        "he",
        "hi",
        "hr",
        "hsb",
        "hu",
        "hy",
        "ig",
        "is",
        "ja",
        "ja-u-co-unihan",
        "ka",
        "kk",
        "kl",
        "km",
        "kn",
        "kn-u-co-trad",
        "ko",
        "ko-u-co-unihan",
        "kok",
        "ku",
        "ky",
        "lkt",
        "ln",
        "ln-u-co-phonetic",
        "lo",
        "lt",
        "lv",
        "mk",
        "ml",
        "mn",
        "mr",
        "mt",
        "my",
        "ne",
        "no",
        "om",
        "or",
        "pa",
        "pl",
        "ps",
        "ro",
        "ru",
        "se",
        "si",
        "si-u-co-dict",
        "sk",
        "sl",
        "smn",
        "sq",
        "sr",
        "sr-Latn",
        "sv",
        "sv-u-co-trad",
        "ta",
        "te",
        "th",
        "tk",
        "to",
        "tr",
        "ug",
        "uk",
        "und",
        "und-u-co-emoji",
        "und-u-co-eor",
        "ur",
        "uz",
        "vi",
        "vi-u-co-trad",
        "wo",
        "yi",
        "yo",
        "zh",
        "zh-u-co-stroke",
        "zh-u-co-unihan",
        "zh-u-co-zhuyin",
    ];
    static DATA: [&DataStruct; 117usize] = [
        &AF, &AM, &AR, &AR, &AR, &AR, &AR, &AM, &AR, &AR, &AR, &AF, &AR, &AR, &AF, &AM, &AF, &AF,
        &DA, &AF, &AF, &AF, &EE, &AM, &AF, &AF, &AF, &AF, &AF, &AR, &AR, &AF, &AF, &AF, &AF, &AF,
        &FR_CA, &AF, &AF, &AR, &AF, &AF, &AM, &AR, &AR, &AF, &AF, &AR, &AF, &AF, &AR, &AR, &AM,
        &AR, &AF, &AR, &AR, &AR, &AR, &AR, &AR, &AR, &AR, &AF, &AF, &AF, &AM, &LT, &AF, &AR, &AR,
        &AM, &AR, &DA, &AR, &AM, &AF, &AF, &AR, &AR, &AF, &AR, &AF, &AM, &AF, &AR, &AR, &AF, &AF,
        &AF, &AF, &AR, &AR, &AF, &AF, &AR, &AR, &TH, &AF, &AF, &AF, &AR, &AR, &UND, &UND, &UND,
        &AR, &AF, &EE, &EE, &AF, &AR, &AF, &AR, &AR, &AR, &AR,
    ];
    KEYS.binary_search_by(|k| locale.strict_cmp(k.as_bytes()).reverse())
        .ok()
        .map(|i| unsafe { *DATA.get_unchecked(i) })
}
static AF: DataStruct = include!("af.rs.data");
static AM: DataStruct = include!("am.rs.data");
static AR: DataStruct = include!("ar.rs.data");
static DA: DataStruct = include!("da.rs.data");
static EE: DataStruct = include!("ee.rs.data");
static FR_CA: DataStruct = include!("fr-CA.rs.data");
static LT: DataStruct = include!("lt.rs.data");
static TH: DataStruct = include!("th.rs.data");
static UND: DataStruct = include!("und.rs.data");
